
name: Flutter CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 3.16.9
    - name: Install dependencies
      run: cd hw && flutter pub get

    - name: Install dependencies
      run: cd hw && flutter pub get

    - name: Format check
      run: cd hw && dart format --set-exit-if-changed .

    - name: Run linter
      run: cd hw && flutter analyze

    - name: Check tests
      run: cd hw && flutter test test
     
    - name: Build APK
      run: cd hw && flutter build apk
