name: Flutter CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.8.1'
        
    - name: Format check
      run: flutter format --set-exit-if-changed .

    - name: Analyze
      run: flutter analyze

    - name: Run linter
      run: flutter pub run lint:lint

    - name: Build APK
      run: flutter build apk

